#
# Jekyll configuration
#
#destination: ./_site
auto:        true
lsi:         true # better related posts
server_port: 3000
pygments:    true
markdown:    rdiscount
rdiscount:
  extensions: []
paginate:    3

exclude: Design, Rakefile, README.textile, lib

#
# Site configuration
#
url:          http://madebynathan.com
permalink:    /:year/:month/:day/:title/index.html
title:        Made by Nathan
description:  ruby & rails, ubuntu linux, iphone, electronics
keywords:     ruby, rails, ubuntu, linux, iphone, electronics, arduino, projects, hobbies
author:       Nathan Broadbent
email:        nathan.f77@gmail.com

#
# Watcher configuration
#
watchers:
  haml:
    path: "_haml"

  image:
    path: "images/posts/"
    sizes:
      post:  [592, 592]
      thumb:  [200, 200]
  jammit:
    assets_file: "_assets.yml"
    command: "jammit -o assets -c _assets.yml"

