#
# Jekyll configuration
#
#destination: ./_site
auto:        true
lsi:         true # better related posts
server_port: 3000
pygments:    true
markdown:    rdiscount
permalink:   /:year/:month/:title.html

rdiscount:
  extensions: []

#
# Site configuration
#
url:          http://ndbroadbent.github.com
title:        Made by Nathan
description:  ruby, rails, linux, iphone, electronics
keywords:     ruby, rails, linux, iphone, electronics
author:       Nathan Broadbent
email:        nathan.f77@gmail.com

exclude: ['haml', 'sass', 'Rakefile', 'README.textile', 'config.rb']

